### ISSUE TITLE
A* algoritma yazımı

### ISSUE THREAD

**Issue by C4MCI** [Navi-IDA/buoy-detection#4]
A* algoritması ros2 modülü olarak yazılacak. Hazır implementasyonlar var, oralardan kopya çekebilir hatta çalışıyorsa direkt copy paste atabiliriz. Test etmek için genelde gazebo veya rviz kullanılmış. Macde sorun olduğu için gazebonun klasik versiyonunu kullanabilir veya direkt rviz üzerinden test edebiilrsiniz hangisi kolay gelirse.

Yararlı olabilecek linkler:
https://youtu.be/jkoGkAd0GYk?si=HGZ1Ntay5ius0B-Q
https://youtu.be/r_2mMyaLLaI?si=W8ujPFhQRoecS8Wo

- [x] Ros2 workspace içerisinde a* modülünü yaz.
- [x] Gazebo veya rviz üzerinde görsel olarak uygula/test et.

**Comment by MustafaSPN** [comment]
videodaki controller ros2 package olarak eklendi ve turtlebot uzerinde calisiyor

**Comment by MustafaSPN** [comment]
https://github.com/user-attachments/assets/139f989d-e249-4da0-9fcb-9f3a1387d722

son durum abi random haritalandirma yapıp uzerinde path finding calistirdik. obje ve haritayı ayni rviz windowda goruntuleyemedigimiz icin boyle saçma görüntü cikti. mouse konumu yaklaşık robot konumuna eşit.

**Comment by C4MCI** [comment]
abim selam, öncelikle ellerine sağlık çok iyi duruyor. Mapi istediğimiz gibi ayarlayabiliriz artık. Videodan anladığım kadarıyla elle goal point veriyoruz. Şu an gördüğüm kadarıyla bunu otomatik hesaplayarak gidebilecek bir geliştirme yapabiliriz bunun üstüne. O yüzden öncelikle mapteki random publishlenen engelleri kırmızı-yeşil-sarı olarak ayırıp yarışmaya benzer bir hale getirmeye çalışalım. Daha sonra mapi listen ederek goal point publishleyen yeni bir ros topici yazalım. Yine gelişme/sıkıntı olursa buradan veya wpden haberleşelim, kolay gelsin.

**Comment by MustafaSPN** [comment]
https://github.com/user-attachments/assets/29bfcb9a-ea00-4413-8a90-97460f2dbc8a

dubalari kimizi,sari ve yeşil olarak publish edildi ve renklerine gore gruplandı. kimizi ve yeşil dubalarda ayni renk olanlar birleştirildi ve kapalı bir yol oluştu.

**Comment by MustafaSPN** [comment]
https://github.com/user-attachments/assets/148dcf80-674d-4d34-8eca-50ec0f062c70

Her yeni duba eklendiğinde yeni bir waypoint atıyor. Çalışıyor ama düzeltmelere ihtiyacı var gibi.

**Comment by C4MCI** [comment]
Abim aşşırı iyi gözüküyor ellerinize emeklerinize sağlık. bundan sonrası havuz başı düzeltmeler olur artık. Gelecek hafta havuz olmasını istiyorum bakalım wpden haberlesiriz.
